export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Navbar} from "./Navbar/Navbar"
export {default as Home} from "./QuizView/Quizview"
export {default as QuizDisplay} from './QuizView/QuizDisplay'
export {default as QuizForm} from './QuizForm/Quizform'
export {default as Userview} from './User/Userview'
export {default as Settings} from './User/Settings'
export {default as Categories} from './Categories'
export {default as Category} from './Category'