# Generated by Django 4.1 on 2023-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_timer_quiz_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
