# Generated by Django 4.1 on 2023-07-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='information',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
