# Generated by Django 4.1 on 2023-08-03 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categorie'),
        ),
    ]
