# Generated by Django 4.1 on 2023-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quiz_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
