export {default as Header} from './Header'
export {default as NextBtn} from './NextBtn'
export {default as Options} from './Options'
export {default as Quote} from './Quote'
export {default as Title} from './Title'